function getRandomMaleName(){
    const maleNames = [
        "barjraj",
        "ramdin verma",
        "sharat chandran",
        "birender mandal",
        "amit",
        "kushal",
        "kasid",
        "shiv prakash",
        "vikram singh",
        "sanjay",
        "abhi",
        "ram dutt gupta",
        "khadak singh",
        "gurmit singh",
        "chanderpal",
        "aman",
        "khursid",
        "rajeev",
        "durgesh",
        "nahar singh",
        "ram kumar",
        "sunder paal",
        "maansingh aswal",
        "rohit",
        "rohit",
        "sparsh",
        "santosh",
        "santosh",
        "punit khandelwal",
        "dinesh",
        "gulshan",
        "arvind kumar yadav",
        "nausad",
        "gurmit singh",
        "md. afsar",
        "shiv shakti singh",
        "moti lal",
        "kausal kumar",
        "rohit",
        "rohit",
        "mohabbat ali",
        "raj kumar",
        "jaswant singh",
        "pitambar lal",
        "chotelal",
        "amit",
        "rupesh",
        "midda",
        "dharam singh",
        "manoj yadav",
        "ram singh",
        "preetam kumar",
        "ram kumar",
        "sarain",
        "pankaj kumar",
        "sheak shakir",
        "riyasat ali",
        "vinit katariya",
        "sumit",
        "arindra",
        "kali charan",
        "badshya khan",
        "vikash",
        "devinder chadda",
        "aman",
        "mohan singh",
        "hemant",
        "shivam",
        "yash mittal",
        "aakash",
        "chandesh",
        "sumit mitra",
        "supriyal sen",
        "gajender singh",
        "pooran chand sharma",
        "irfan",
        "azaruddin",
        "mukul yadav",
        "pooran chand sharma",
        "manoj",
        "sanjay charee",
        "raja babu",
        "goldy",
        "satyender",
        "devender",
        "veer",
        "ankush",
        "mohd. amir",
        "babloo",
        "bhavesh dass",
        "gourav",
        "sunil",
        "guddu rai",
        "yogesh rawat",
        "amarapal",
        "rajesh agarwal",
        "tara singh rawat",
        "momin",
        "parnav kumar",
        "neeraj kumar",
        "parminder",
        "mustafa",
        "ajay haldar",
        "sanjay",
        "dharmender",
        "gaurav sethi",
        "suresh",
        "rohit",
        "dinesh",
        "sachin kumar",
        "sagar",
        "vipin",
        "parth madan",
        "kuldeep",
        "abhimanyu",
        "pawan kumar",
        "rohan",
        "raju garg",
        "samir mishra",
        "ram dayal",
        "jagdish chand",
        "kanheya",
        "deepak",
        "mushrraf",
        "prem",
        "pardeep kumar",
        "monu",
        "pawan",
        "manoj kumar",
        "deepak",
        "nithyanandham",
        "deepak goyal",
        "sunil ladkani",
        "ajay",
        "gopal",
        "vivek",
        "mahavir",
        "indra sain",
        "soni",
        "arun kumar",
        "ashok sharma",
        "veer singh",
        "aman dahiya",
        "pawan",
        "laxmi narayan",
        "vikram dubey",
        "rima",
        "suraj",
        "virender",
        "tara singh rawat",
        "ramjan khan",
        "sunder",
        "omparkash",
        "saddam",
        "alok tiwari",
        "vude bhadur",
        "prem singh bidla",
        "chetanya swaroop",
        "pinkoo guddu",
        "shardanand",
        "vikash",
        "henkhochon haokip",
        "gaurav shankar",
        "shsi kant",
        "md. tavrej",
        "amrudin",
        "shahnawaz",
        "brij raj",
        "aman kumar",
        "dinesh",
        "vijay kumar",
        "baban suresh",
        "subham kumar yadav",
        "sapna",
        "surendra",
        "naveen",
        "ram niwas",
        "amar",
        "nanhu khan",
        "kishan",
        "dharmender",
        "raja ram",
        "rishab",
        "ziyabul",
        "jag mohan",
        "devender",
        "ritu raj kumar",
        "manoj kumar",
        "raj kapoor",
        "arvind agarwal",
        "rajbir ahlawat",
        "mohd faijan",
        "suraj",
        "shyama",
        "firoz",
        "jagdish",
        "bhag chand",
        "sachin",
        "parbhat",
        "aamod",
        "pramod",
        "chander shekhar",
        "nanagram",
        "gautam",
        "mohan",
        "govind",
        "raja babu",
        "pramjot singh",
        "abhinav vashit",
        "usha",
        "vivek chabra",
        "ashish",
        "ankit",
        "harish chand",
        "nootan prakash yadav",
        "surender",
        "chhotelal",
        "karan",
        "karan",
        "abdul kadir",
        "vikas kumar",
        "sambhu",
        "bablu",
        "bablu"
    ];
    const randomNum = Math.floor(Math.random()*(maleNames.length+1));
    return maleNames[randomNum];
}
function getRandomFemaleName(){
    const femaleNames = [
        "shivani",
        "isha",
        "divya",
        "mansi",
        "mazida",
        "pooja",
        "kajal",
        "meena",
        "sonam",
        "buity",
        "hina",
        "shakshi sagar",
        "pooja",
        "anita",
        "neetu",
        "kanika kathuria",
        "manju",
        "shakshi",
        "anita",
        "reena",
        "neha",
        "khushboo",
        "aasmin",
        "jyoti",
        "riya masi",
        "rekha",
        "leela with a child",
        "isha",
        "gulshan",
        "priya jain",
        "pooja",
        "versha",
        "sunita",
        "nitu kumari",
        "vandana",
        "roshni",
        "parveen",
        "versa",
        "kavita",
        "pooja",
        "sarojani",
        "nagina",
        "tapas das",
        "priyanka",
        "santna",
        "khushbu",
        "pooja",
        "any bobby",
        "deeya kumari",
        "anjali juneja",
        "champa karketta",
        "anshu",
        "monika",
        "rimmi singh",
        "aanamika misra",
        "chahat",
        "manju",
        "nagma khatoon",
        "pooja",
        "sonam",
        "koshal",
        "sandhya",
        "poonam",
        "sna",
        "nikita senger",
        "layba noor",
        "iqra",
        "salima",
        "naziya",
        "priti",
        "kamni",
        "sandhya",
        "rinki",
        "priya",
        "pooja",
        "minakchi",
        "ruby",
        "farhana baigum",
        "sheetal",
        "kalyani patro",
        "anjali",
        "priyanka",
        "simran",
        "babita",
        "gurdeep kaur",
        "dhanwanti  devi",
        "fooljhnah",
        "vandana",
        "gyatri devi",
        "shehnaz",
        "kajal",
    ];
    const randomNum = Math.floor(Math.random()*(femaleNames.length+1));
    return femaleNames[randomNum];
}
function getRandomInt(){
    return Math.floor(Math.random()*10)
}
function getRandomIntBetweenRange(min,max){
    if(Number.isInteger(max) && Number.isInteger(min)){
        return Math.floor(Math.random() * (max - min + 1) + min);
    }
    else{
        min = Math.ceil(min);
        max = Math.floor(max);
        return Math.floor(Math.random() * (max - min + 1) + min);
    }
}
module.exports = {
    getRandomMaleName,
    getRandomFemaleName,
    getRandomInt,
    getRandomIntBetweenRange
}
